import { TESTNET_TESTCOIN_PACKAGE_OBJECT_ID } from "../config";

export const SUI_COIN_TYPE = "0x2::sui::SUI";
export const TESTNET_USDT_COIN_TYPE = `${TESTNET_TESTCOIN_PACKAGE_OBJECT_ID}::coins::USDT`;
export const TESTNET_XBTC_COIN_TYPE = `${TESTNET_TESTCOIN_PACKAGE_OBJECT_ID}::coins::XBTC`;
export const TESTNET_WBTC_COIN_TYPE = `${TESTNET_TESTCOIN_PACKAGE_OBJECT_ID}::coins::WBTC`;
export const TESTNET_BTC_COIN_TYPE = `${TESTNET_TESTCOIN_PACKAGE_OBJECT_ID}::coins::BTC`;
export const TESTNET_ETH_COIN_TYPE = `${TESTNET_TESTCOIN_PACKAGE_OBJECT_ID}::coins::ETH`;
export const TESTNET_BNB_COIN_TYPE = `${TESTNET_TESTCOIN_PACKAGE_OBJECT_ID}::coins::BNB`;
export const TESTNET_DAI_COIN_TYPE = `${TESTNET_TESTCOIN_PACKAGE_OBJECT_ID}::coins::DAI`;
export const TESTNET_USDC_COIN_TYPE = `${TESTNET_TESTCOIN_PACKAGE_OBJECT_ID}::coins::USDC`;

export const FEE_MULTIPLIER = 30;
export const FEE_SCALE = 10000;